// src/components/organisms/Contributors/index.tsx
import React from 'react';
import styled from '@Styles/styled';
import Subtitle from '@Atoms/Subtitle';
import Button from '@Atoms/Button';
import Description from '@Atoms/Description';
import MapGridUsers from '@Organisms/MapGridUsers';
import PropTypes from 'prop-types';

type ContributorsProps = {
  title?: string;
  description?: string;
};

const StyleContributors = styled.div`
  display: grid;
  grid-template-columns: 1fr;
  width: 100%;
  height: max-content;
  padding: 100px 0px 48px 0px;
  border-bottom: solid #d9d9d9 1px;
  h2 {
    margin-top: -90px;
    @media (max-width: 1140px) {
      margin-top: 0px;
      margin-bottom: 48px;
      width: 60%;
      justify-self: center;
    }
  }
  p {
    margin-top: -60px;
    @media (max-width: 1140px) {
      margin-top: 0px;
    }
  }
  button {
    margin-top: 0px;
    @media (max-width: 1140px) {
      margin-top: 16px;
    }
  }
  @media (max-width: 1140px) {
    padding: 64px 0px 64px 0px;
  }

  .contributors {
    display: flex;
    justify-content: center;
    align-items: center;
  }
  h2:nth-of-type(1) {
    text-align: center;
  }
  .invitacion {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin: auto;
    p {
      text-align: center;
      width: 50%;
    }
    button {
      margin-left: 0px;
    }
  }
  @media (min-width: 1140px) {
    grid-template-columns: repeat(2, 1fr);
    .contributors {
      width: 100%;
      height: 100%;
      grid-column: 1/2;
      grid-row: 1/3;
      justify-content: flex-end;
      padding-right: 110px;
    }
    .invitacion {
      grid-column: 2/3;
      align-items: flex-start;
      p {
        text-align: left;
        width: 95%;
      }
    }
    h2:nth-of-type(1) {
      grid-row: 1/2;
      align-self: flex-end;
      text-align: start;
    }
    div:nth-of-type(2) {
      grid-column: 2/3;
    }
  }
`;

const Contributors: React.FC<ContributorsProps> = ({ title, description }) => (
  <StyleContributors>
    <Subtitle size="sub1" as="h2">
      {title}
    </Subtitle>
    <div className="contributors">
      <MapGridUsers />
    </div>
    <div className="invitacion">
      <Description size="lg">{description}</Description>
      <Button text="Conócelos a todos" size="md" />
    </div>
  </StyleContributors>
);

Contributors.propTypes = {
  title: PropTypes.string,
  description: PropTypes.string
};
Contributors.defaultProps = {
  title: 'Ellos son parte de nuestra comunidad',
  description:
    'En los proyectos de la comunidad hay personas de todo el mundo que aporta su tiempo, conocimiento y experiencia con los demas'
};

export default Contributors;

// src/routes/_sections/Contributors.svelte
<script>
  import Button from '@components/Button'
  import MapGrid from '@components/MapGrid'
</script>

<section id="contributors">
  <div class="container">
    <h2 class="subtitle">Ellos son parte de nuestra comunidad</h2>
    <article class="map-community">
      <MapGrid />
    </article>
    <article class="message">
      <p class="text">
        En los proyectos de la comunidad hay personas del todo el mundo que
        aporta su tiempo, conocimiento y experiencia con los demás.
      </p>
      <Button primary fill large>Conócelos a todos</Button>
    </article>
  </div>
</section>

<style lang="scss">
  @import 'src/styles/utils';

  section {
    padding-top: $size-7xl;
    padding-bottom: $size-7xl;

    .container {
      display: grid;
      gap: $size-2xl;
      justify-items: center;
      grid-template-columns: fit-content(100%);
      grid-template-rows: repeat(3, fit-content(100%));

      .subtitle {
        margin-bottom: $size-2xl;
      }

      .message {
        display: grid;
        gap: $size-2xl;
        justify-items: center;
      }
    }
  }

  @include media(lg) {
    section {
      .container {
        .subtitle {
          text-align: center;
        }

        .message {
          .text {
            text-align: center;
          }
        }
      }
    }
  }

  @include media(xl) {
    section {
      padding-top: 7.5rem;
      padding-bottom: $size-5xl;

      .container {
        column-gap: $size-7xl;
        grid-template-areas:
          'mapgrid subtitle subtitle'
          'mapgrid message message';

        .map-community {
          grid-area: mapgrid;
        }

        .subtitle {
          grid-area: subtitle;
          text-align: left;
          margin-bottom: 0;
        }

        .message {
          grid-area: message;
          justify-items: left;

          .text {
            text-align: left;
          }
        }
      }
    }
  }
</style>
