// src/components/organisms/Projects/index.tsx
import React from 'react';
import styled from '@Styles/styled';
import CardGroupProjects from '@Organisms/CardGroupProjects';
import Subtitle from '@Atoms/Subtitle';
import Description from '@Atoms/Description';
import { screen } from '@Styles/theme';

const StyleProjects = styled.section`
  width: 100%;
  min-height: calc(100vh - 90px);
  height: max-content;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: ${({ theme }) => theme.color.secondary.light};
  .backgroundImages {
    z-index: 0;
    position: absolute;
    width: 100vw;
    display: none;
    justify-content: space-between;

    ${screen('xl')} {
      display: flex;
    }
  }
  .descripcion {
    z-index: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    margin: 50px 0px 50px 0px;

    &-ContainerTitle {
      display: flex;
      flex-direction: column;
      align-items: center;
      width: max-content;

      h2 {
        padding-top: 100px;
        width: max-content;
        @media (max-width: 1140px) {
          padding-top: 64px;
        }
        @media (max-width: 720px) {
          width: 300px;
          padding-top: 0px;
        }
      }
      p {
        width: 650px;
        @media (max-width: 720px) {
          width: 300px;
        }
        padding-bottom: 42px;
      }
    }
  }
`;

const Projects: React.FC = () => (
  <StyleProjects>
    <div className="backgroundImages">
      <img src="/images/CircuitoLeft.svg" alt="" />
      <img src="/images/CircuitoRight.svg" alt="" />
    </div>
    <div className="descripcion">
      <div className="descripcion-ContainerTitle">
        <Subtitle align="center" white size="sub1">
          Proyectos de la comunidad
        </Subtitle>
        <Description size="xl" align="center" white>
          En la comunidad podrás encontrar distintos proyectos para colaborar en diferentes tecnologias.
          Tenemos 4 proyectos principales que son:
        </Description>
      </div>
      <CardGroupProjects />
    </div>
  </StyleProjects>
);

export default Projects;

// src/routes/_sections/Projects.svelte
<script>
    import ProjectCard from '@components/ProjectCard'
</script>

<section class="projects">
    <div class="circuit-background">
        <img src="/images/circuito_left.svg" alt="">
        <img src="/images/circuito_right.svg" alt="">
    </div>
    <div class="container">
        <article class="message">
            <h2 class="subtitle white">Proyectos de la comunidad</h2>
            <p class="text white">
                En la comunidad podrás encontrar distintos proyectos para colaborar en diferentes tecnologias.
                Tenemos 4 proyectos principales que son:
            </p>
        </article>
        <article class="grid-projects">
            <ProjectCard
                icon="web"
                title="Fazt Web"
                label="Repositorio de Fazt Web"
                link="https://github.com/faztcommunity/fazt-oficial-web"
                desc="Es la web oficial de Fazt Community donde se colocan los proyectos y aportes de los integrandes de la comunidad." />
            <ProjectCard
                icon="api"
                title="Fazt Api"
                label="Repositorio de Fazt Api"
                link="https://github.com/faztcommunity/fazt-api"
                desc="Es el núcleo de los proyectos principales, este proyecto se encargará de unificar la base de datos con los demás proyectos." />
            <ProjectCard
                icon="bot"
                title="Fazt Bot"
                label="Repositorio de Fazt Bot"
                link="https://github.com/faztcommunity/fazt-bot"
                desc="Un bot para Discord multipropósito capaz de realizar distintas actividades como saludos, reproducir música y mucho más." />
            <ProjectCard
                icon="database"
                title="Fazt Database"
                label="Repositorio de Fazt Database"
                link="https://github.com/faztcommunity/fazt-methodology-core"
                desc="Analizamos distintos ámbitos de los proyectos comunitarios, para poder guardar todos los registros y/o datos." />
        </article>
    </div>
</section>

<style lang="scss">
    @import 'src/styles/utils';

    section {
        padding-top: $size-7xl;
        padding-bottom: $size-7xl;
        background: $color-secondary-light;

        .circuit-background {
            width: 100%;
            display: none;
            position: absolute;
            z-index: $z-0;
        }

        .container {
            display: grid;
            position: relative;
            gap: $size-4xl;
            grid-template-rows: repeat(2, fit-content(100%));
            z-index: $z-10;

            .message {
                display: grid;
                gap: $size-base;
                max-width: 696px;
                justify-self: center;
            }

            .grid-projects {
                display: grid;
                gap: $size-3xl;
                justify-content: center;
                grid-template-rows: repeat(4, fit-content(100%));
            }
        }
    }

    @include media(lg) {
        section {
            padding-top: 9.75rem;
            padding-bottom: 9.75rem;

            .circuit-background {
                display: flex;
                justify-content: space-between;
            }

            .container {
                .message {
                    h2, p {
                        text-align: center;
                    }
                }

                .grid-projects {
                    grid-template-rows: repeat(2, fit-content(100%));
                    grid-template-columns: repeat(2, fit-content(100%));
                }
            }
        }
    }
</style>
