// src/components/organisms/Footer/index.tsx
import React from 'react';
import styled from '@Styles/styled';
import Description from '@Atoms/Description';
import Icon from '@Atoms/Icon';

const DISCORD_LINK = 'https://discord.com/invite/37PHuNw';
const GITHUB_LINK = 'https://github.com/faztcommunity';

const StyledFooter = styled.footer`
  width: 100%;
  color: white;
  text-align: center;
  font-family: 'Roboto';
  padding-top: 1.5rem;
  padding-bottom: 1.5rem;
  background: ${({ theme }) => theme.neutrale.gray[800]};
`;

const FooterContent = styled.section`
  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: repeat(3, auto);
  grid-row-gap: 1rem;
  grid-template-areas:
    'copyright'
    'title'
    'link-icons';

  & a {
    margin-left: 0.5rem;
    margin-right: 0.5rem;
  }

  @media (min-width: 768px) {
    grid-template-columns: repeat(3, 1fr);
    grid-template-rows: auto;
    grid-row-gap: 0;
    grid-template-areas: 'copyright' 'title' 'link-icons';
    align-items: center;

    a {
      margin-left: 1rem;
      margin-right: 1rem;
    }
  }
`;

const Footer: React.FC = () => (
  <StyledFooter>
    <FooterContent>
      <Description center white>
        All right reserved 2020
      </Description>
      <Description center white>
        Fazt Community
      </Description>
      <span>
        <a rel="noopener noreferrer" href={DISCORD_LINK} target="_blank">
          <Icon size="rl" icon="discord" />
        </a>
        <a rel="noopener noreferrer" href={GITHUB_LINK} target="_blank">
          <Icon size="rl" icon="github" />
        </a>
      </span>
    </FooterContent>
  </StyledFooter>
);

export default Footer;

// src/components/Footer.svelte
<script>
  import Link from '@components/Link.svelte'
  import Icon from '@components/Icon.svelte'
  import { socials } from '@utils/constants'
</script>

<footer>
  <div class="content">
    <span class="copy-left">All rights not reserved 2021</span>
    <span class="community">Fazt Community</span>
    <ul class="socials">
      <li>
        <Link external to={socials.DISCORD} alt="Discord">
          <Icon name="discord" size="32" color="white" />
        </Link>
      </li>
      <li>
        <Link external to={socials.GITHUB} alt="Github">
          <Icon name="github" size="32" color="white" />
        </Link>
      </li>
    </ul>
  </div>
</footer>

<style lang="scss">
  @use 'sass:map';
  @import 'src/styles/utils';

  footer {
    display: grid;
    background: $black;

    .content {
      width: 100%;
      display: grid;
      color: white;
      gap: $size-base;
      justify-self: center;
      justify-items: center;
      padding-top: $size-2xl;
      padding-bottom: $size-2xl;
      max-width: map.get($breakpoints, 2xl);
      grid-template-rows: repeat(3, fit-content(100%));

      .copy-left {
        font-weight: 700;
      }

      .socials {
        display: grid;
        gap: $size-2xl;
        justify-content: center;
        grid-template-columns: repeat(2, fit-content(100%));
      }
    }
  }

  @include media(lg) {
    footer {
      .content {
        align-items: center;
        padding-top: $size-lg;
        padding-bottom: $size-lg;
        grid-template-rows: fit-content(100%);
        grid-template-columns: repeat(3, 1fr);

        .copy-left {
          font-weight: 400;
        }

        .socials {
          display: grid;
          gap: $size-2xl;
          justify-content: center;
          grid-template-columns: repeat(2, fit-content(100%));
        }
      }
    }
  }
</style>
